<html>
<head>
    <style type="text/css" >
        h1 {
            color: #000000;
            font-family: Georgia;
            font-size: 80%;
        }

        h2 {
            color: #000000;
            font-family: Georgia;
            font-size: 80%;
        }

        h3 {
            color: #000000;
            font-family: Georgia;
            font-size: 80%;
        }

        p {
            color: black;
            font-size: 80%;
            font-family: Georgia;
        }
        .button2 {background-color: #1c7791;}
        .button3 {background-color: #1c7791;}
        .button4 {background-color: #910608;}
    </style>
</head>
<body>
<form  name="user" method="post" action="Login">
    <h2 class="Container">
        <label><h1>Username</h1></label>
        <input type="text" placeholder="Enter Email" name="u_Email"  value="" required>

        <label><h1>Password</h1></label>
        <input type="password" placeholder="Password" name="pass_word"  value="">

        <h2><input  type="checkbox" checked = "checked" name="remember_me"> Remember me </h2>
    </h2>
    <div class="button" style="background-color: #f6ffed">
        <button type="submit" class="button2">Login</button>
        <button type="reset" class="button3">Cancel</button>

        <h1> <span   class="psw" >Forgot <a href="http://test1.com/users/ForgotPassword" name="forgot_passw" >password?</a></span></h1>

    </div>
    <h1><button><strong><a href="register" name="sign"   class="button">Sign up</a> </strong></button></h1>
</form>
</body>
</html>




