<html>
<head>
    <style type="text/css" >

        .form  {
         text-align: center;
         padding: auto;
         display: inline-block;
         align-items: center;
         margin: auto;

        }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
</head>
<body>
<form class="form ">
    <div class="form-group center-block">
        <label  for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="Email1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group center_div">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <button id="Submit" type="submit" class="btn btn-primary btn-sm">Submit</button>
    <button id ="Sign Up" type="submit" class="btn btn-primary  btn-sm">Sign up</button>
</form>

</body>

 <script>
     $(document).ready(function () {

         $('#Submit').click( function () {

             $.ajax({
                 url: '/admin/login',
                 type: 'POST',
                 dataType: 'json',
                 data: {
                     user : document.getElementById('Email1').value,
                     password : document.getElementById('exampleInputPassword1').value,

                 },
                 error : function (errr) {
                     console.log(errr)
                 },
                 success: function(components) {

                      alert(components)
                 }
             });
         });


     });
 </script>
</html>




