

<html>
<head>
    <style type="text/css">

   .Container {
       text-align: center;
       display: block;
       margin: auto;
       width: 300px;
       padding: 50px;
   }
   .submit {
       text-align: center;
        display: block;
        margin: 20px;

   }

   h1 {
       color: #000000;
       font-family: Georgia;
       font-size: 80%;
   }

   h2 {
       color: #000000;
       font-family: Georgia;
       font-size: 80%;
   }

   h3 {
       color: #000000;
       font-family: Georgia;
       font-size: 80%;
   }

  p {
      margin: auto;
      color: black;
      font-size: 80%;
      font-family: Georgia;
  }


  .button {
      background-color: #1c7791;
      border: none;
      color: white;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
  }

   .button2 {background-color: #1c7791;}
   .button3 {background-color: #1c7791;}

    </style>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

    <script type="text/javascript">

        var time = new Date();

        $(document).ready(function () {

            $('#button').click( function () {

                $.ajax({
                    url: '/admin/register',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        time : time,
                        user : document.getElementById('name').value,
                        email : document.getElementById('Email').value,
                        password_ret : document.getElementById('password').value,
                        password : document.getElementById('password1').value

                    },
                    error : function (errror) {

                    },
                    success: function(date) {

                        if(date.error == true){

                            alert(date.message);
                            alert('Please enter corect email or UserName')
                        }

                            location.href = 'http://test1.com/admin/'+date.href


                    }
                });
            });


        });


    </script>

</head>
<body>

<div class="Container">

    <label><h1>UserName</h1></label>
    <input id="name" type="text" name="u_name" placeholder="Your user name"  required>

    <label><h2>Email</h2></label>
    <input id="Email" type="text" placeholder="Enter email" name="u_Email" required>

    <label><h2>Password</h2></label>
    <input id="password" type="password" placeholder="Enter Password" name="pass_word" required>

    <label><h3>Reapeat Password</h3></label>

    <input id="password1" type="password" placeholder="Repeat Password" name="pass_repeat" required>

    <div class="Submit">

        <button class="button2" type="button" >Cancel</button>

        <button  id="button" class="button3" type="button">Sign Up</button>

    </div>
<div>

<p><a href="https://www.google.com/policies/privacy/"  >Terms & Privacy</p>
</body>
</html>